import os
import re

from freezegun import freeze_time
from django.core.management import call_command
import django.test

from tests.helpers import cleanup_migrations


def snapshot_transformer(content):
    lines = content.splitlines()

    # ignore all header lines
    for header in ["# -*- coding:", "# Generated by Django", "from __future__ import unicode_literals"]:
        lines = [l for l in lines if not l.startswith(header)]

    # remove "initial = True" line
    lines = [l for l in lines if "initial = True" not in l]

    # reorder "AutoField()" keyword arguments
    def _reorder_kwargs(line):
        if "AutoField(" in line:
            kwargs = re.search(r'AutoField\(([^\)]+)\)', line).groups(0)[0]
            sorted_kwargs = ", ".join(sorted(kwargs.split(", ")))
            line = line.replace(kwargs, sorted_kwargs)

        return line
    lines = map(_reorder_kwargs, lines)

    # remove some SQL comments for django < 1.9
    # django 1.8- didn't have comments on SQL instructions
    if django.VERSION < (1, 9):
        lines = [l for l in lines if not l.startswith("# --")]

    # remove blank lines
    lines = [l for l in lines if l]

    return "\n".join(lines)


class TestMakemigrationsAddsSql(django.test.TestCase):
    def tearDown(self):
        cleanup_migrations()

    @freeze_time("2017-12-01")
    def test_makemigrations_adds_a_migration_file(self):
        call_command("makemigrations", "example_app")
        assert os.path.isfile("tests/example_app/migrations/0001_initial.py")

        content = open("tests/example_app/migrations/0001_initial.py").read()
        content.should.match_snapshot("migrations__0001_initial.py", snapshot_transformer)
