import os

from freezegun import freeze_time
from django.core.management import call_command
import django.test

from tests.helpers import cleanup_migrations


def ignore_django_version_line(content):
    lines = content.splitlines()
    lines = [l for l in lines if not l.startswith("# Generated by Django")]
    return "\n".join(lines)


class TestMakemigrationsAddsSql(django.test.TestCase):
    def tearDown(self):
        cleanup_migrations()

    @freeze_time("2017-12-01")
    def test_makemigrations_adds_a_migration_file(self):
        call_command("makemigrations", "example_app")
        assert os.path.isfile("tests/example_app/migrations/0001_initial.py")

        content = open("tests/example_app/migrations/0001_initial.py").read()
        content.should.match_snapshot("migrations__0001_initial.py", ignore_django_version_line)
