name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
      
jobs:
  build:
    name: "empty"
    runs-on: ubuntu-latest

    steps:
      - name: Yay
        run: "true"

  report-status:
    name: success
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Report success
        run: echo 'Success !'
